### ISSUE TITLE
gpm installation fails with grav 1.6.x

### ISSUE THREAD

**Issue by bitstarr** [trilbymedia/grav-plugin-color-tools#1]
as statet in the title…

in the develop branch the dependency on 1.7. seems to be removed.

**Comment by rhukster** [comment]
GPM installation of what? Can you provide some more details of what exact version you are running and what command you are trying?

**Comment by bitstarr** [comment]
I'm running the latest version of grav 1.6 and was trying to install the plugin via ``bin/gpm install color-tools``as described in the readme. It returns saying that it depends on grav 1.7.0rc.16 (as currently stated in blueprint.yaml of the master branch)
