### ISSUE TITLE
add support for color names

### ISSUE THREAD

**Issue by dani-ooo** [trilbymedia/grav-plugin-color-tools#4]
mexitek/phpColors has added a `nameToHex` function for this: https://github.com/mexitek/phpColors/blob/4043974240ca7dc3c2bec3c158588148b605b206/src/Mexitek/PHPColors/Color.php#L241

**Comment by rhukster** [comment]
Give the latest develop branch a try

**Comment by dani-ooo** [comment]
hey. sorry, i was absent for the holidays.

i just tried to test it, but got this error:
> An exception has been thrown during the rendering of a template ("include(/user/plugins/color-tools/vendor/composer/../mexitek/phpcolors/src/Mexitek/PHPColors/Color.php): Failed to open stream: No such file or directory").

is it because it’s referencing files outside the repository?

**Comment by rhukster** [comment]
No my fault, the `phpcolors` folder was commited as a git-submodule.  I've fixed this now.  Please try again.

**Comment by dani-ooo** [comment]
working great! thanks!

it would be swell if the `color` function detected the input color format; so, if you did something like `'tomato'|color` or `'hsl(9.13, 100%, 63.92%)'|color`, it would work just fine. should i suggest this idea in a separate issue?

**Comment by rhukster** [comment]
I don't think it's a good idea.  The `name_to_hex` function/filter return a string, whereas the `color` function/filter return a color object.

You would use them both like this:

```twig
('tomato'|name_to_hex)|color
```
